# Dart Analyzer Configuration für MSA Analysis
# 
# Kontrolliert Code-Qualität und Best-Practices

analyzer:
  # Wähle die rekursiv zu analysierenden Roots
  include:
    - lib/**/*.dart
    - test/**/*.dart
    - bin/**/*.dart

  # Fehler Schweregrade
  errors:
    # Null Safety Fehler - kritisch
    missing_required_param: error
    missing_return: error
    todo: ignore

    # Best Practice Fehler
    always_declare_return_types: error
    always_put_control_body_on_new_line: warning
    always_put_required_named_parameters_first: warning
    annotate_overrides: warning
    avoid_bool_literals_in_conditional_expressions: warning
    avoid_double_and_int_checks: warning
    avoid_empty_else: error
    avoid_field_initializing_in_constructor_body: warning
    avoid_function_literals_in_foreach_calls: warning
    avoid_init_to_null: warning
    avoid_null_checks_in_equality_operators: warning
    avoid_private_typedef_functions: warning
    avoid_relative_lib_imports: error
    avoid_renaming_method_parameters: warning
    avoid_returning_null: warning
    avoid_returning_null_for_future: warning
    avoid_returning_null_for_void: warning
    avoid_returning_this: warning
    avoid_setters_without_getters: warning
    avoid_shadowing_type_parameters: warning
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    avoid_types_unrelated_to_declaration: error
    avoid_unknown_extensions: error
    avoid_unnecessary_containers: warning
    avoid_void_async: error
    await_only_futures: error
    camel_case_extensions: warning
    camel_case_types: error
    cascade_invocations: warning
    cast_nullable_to_non_nullable: error
    close_sinks: warning
    comment_references: warning
    conditional_uri_does_not_exist: warning
    constant_identifier_names: error
    control_flow_in_finally: error
    curly_braces_in_flow_control_structures: warning
    dangling_library_doc_comments: warning
    depend_on_referenced_packages: error
    deprecated_consistency: warning
    deprecated_member_use_from_same_package: ignore
    empty_catches: error
    empty_constructor_bodies: error
    empty_statements: error
    eol_only_unix_line_endings: ignore
    exhaustive_cases: warning
    file_names: error
    hash_and_equals: error
    implementation_imports: error
    invariant_booleans: warning
    iterable_contains_unrelated_type: error
    leading_newlines_in_multiline_strings: warning
    library_names: error
    library_prefixes: error
    library_private_types_in_public_api: error
    lines_longer_than_80_chars: ignore
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: error
    matching_super_parameters: warning
    missing_whitespace_between_adjacent_strings: error
    no_adjacent_strings_in_list: error
    no_leading_underscores_for_library_prefixes: error
    no_leading_underscores_for_local_variables: error
    null_aware_operator_assignment_operators: error
    null_check_always_fails: error
    null_closures: error
    omit_local_variable_types: ignore
    one_member_abstracts: warning
    only_throw_errors: warning
    overridden_fields: error
    package_api_docs: warning
    package_names: error
    package_prefixed_library_names: error
    parameter_assignments: warning
    prefer_adjacent_string_concatenation: warning
    prefer_asserts_in_initializer_lists: warning
    prefer_asserts_with_message: warning
    prefer_collection_literals: warning
    prefer_conditional_assignment: warning
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_constructors_over_static_methods: warning
    prefer_contains: warning
    prefer_equal_for_default_values: warning
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_final_locals: warning
    prefer_for_elements_to_map_fromIterable: warning
    prefer_foreach: ignore
    prefer_function_declarations_over_variables: warning
    prefer_generic_function_type_aliases: warning
    prefer_if_elements_to_conditional_expressions: warning
    prefer_if_null_to_conditional_expressions: warning
    prefer_if_on_single_line_is_else: ignore
    prefer_initializing_formals: warning
    prefer_inlined_adds: warning
    prefer_int_literals: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_is_not_operator: warning
    prefer_is_null_check_on_cascade_expressions: warning
    prefer_null_aware_operators: warning
    prefer_null_coalescing_operator: warning
    prefer_relative_import: ignore
    prefer_single_quotes: warning
    prefer_spread_collections: warning
    provide_deprecation_message: error
    recursive_getters: error
    sized_box_for_whitespace: warning
    sized_box_shrink_expand: warning
    sized_box_to_limit_height: warning
    sized_box_to_limit_width: warning
    slash_for_doc_comments: warning
    sort_child_properties_last: warning
    sort_constructors_first: warning
    sort_pub_dependencies: warning
    sort_unnamed_constructors_first: warning
    tighten_type_of_initializing_formals: warning
    type_annotate_public_apis: warning
    type_init_formals: warning
    type_literal_in_constant_pattern: error
    unawaited_futures: error
    unnecessary_await_in_return: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_constructor_name: warning
    unnecessary_getters_setters: warning
    unnecessary_lambdas: warning
    unnecessary_new: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_checks: error
    unnecessary_null_in_if_null_operators: warning
    unnecessary_null_keyword: warning
    unnecessary_nullable_for_final_variable_declarations: error
    unnecessary_overrides: warning
    unnecessary_parenthesis: warning
    unnecessary_string_escapes: warning
    unnecessary_string_interpolations: warning
    unnecessary_this: warning
    unnecessary_to_list_in_spreads: warning
    unrelated_type_equality_checks: error
    unsafe_html: error
    use_build_context_synchronously: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_getters_to_change_properties: warning
    use_if_null_to_convert_nulls: warning
    use_is_even_rather_than_modulo: warning
    use_key_in_widget_constructors: warning
    use_late_for_private_fields_and_variables: warning
    use_named_constants: warning
    use_raw_strings: warning
    use_rethrow_when_possible: warning
    use_setters_to_change_properties: warning
    use_string_buffers: warning
    use_test_throws_matchers: warning
    use_to_close_resource: warning
    use_to_close_resources: error
    void_checks: error

  # Exclude
  exclude:
    - 'bin/cache/**'
    - 'lib/generated/**'
    - 'lib/src/generated/**'
